import { Flex, Box } from '@chakra-ui/react';

import Head from 'next/head';

import { FirstPaint } from '../components/FirstPaint';
import { Manifesto } from '../components/Manifesto';
import { Services } from '../components/Services';
import { Portfolio } from '../components/Portfolio';
import { Culture } from '../components/Culture';
import { Token } from '../components/Token';
import { Community } from '../components/Community';

import { Footer } from '../shared/Footer';

export default function Home() {
  return (
    <Flex height='100%' width='100%' direction='column'>
      <Head>
        <title>RaidGuild</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css'
          integrity='sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=='
          crossorigin='anonymous'
        />
        <script
          src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js'
          integrity='sha512-YSdqvJoZr83hj76AIVdOcvLWYMWzy6sJyIMic2aQz5kh2bPTd9dzY3NtdeEAzPp/PhgZqr4aJObB3ym/vsItMg=='
          crossorigin='anonymous'
        ></script>
      </Head>

      <FirstPaint />
      <Manifesto />
      <Services />
      <Portfolio />
      <Culture />

      <Token />

      <Community />

      <Box
        px='5rem'
        py='2rem'
        minH='20vh'
        bgImage='url(/assets/layered-steps.png)'
      ></Box>

      <Footer />
      {/* <Text fontFamily='jetbrains' color='red' py='.5rem' ml='auto' mr='auto'>
        &copy; 2021, RaidGuild
      </Text> */}
    </Flex>
  );
}
