import { Flex } from '@chakra-ui/react';

import Head from 'next/head';

import { FirstPaint } from '../components/FirstPaint';
import { Manifesto } from '../components/Manifesto';
import { Services } from '../components/Services';
import { Portfolio } from '../components/Portfolio';
import { Culture } from '../components/Culture';

import { Footer } from '../shared/Footer';

export default function Home() {
  return (
    <Flex height='100%' width='100%' direction='column'>
      <Head>
        <title>RaidGuild</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <FirstPaint />
      <Manifesto />
      <Services />
      <Portfolio />
      <Culture />

      <Footer />
    </Flex>
  );
}
